import type { AiProviderAdapter, AiRequest, AiResponse, ProviderSettings } from '../types/ai.js';

declare global { interface Window { __ENV__?: Record<string,string>; } }
const jsonHeaders = { 'Content-Type': 'application/json' };
export function env(name: string): string { return (typeof window !== 'undefined' && window.__ENV__?.[name]) || ''; }
function authHeaders(providerId: string): Record<string, string> { const key = env(`VITE_${providerId.toUpperCase()}_API_KEY`); return key ? { Authorization: `Bearer ${key}` } : {}; }
function demoReply(prompt: string): string { const lower=prompt.toLowerCase(); if(lower.includes('banjir')) return 'Demo: Untuk banjir, semak paras air, elakkan laluan rendah, sediakan beg kecemasan, dan hubungi 999 jika keselamatan terancam.'; if(lower.includes('gempa')) return 'Demo: Berlindung di bawah meja kukuh, jauhi tingkap, dan keluar selepas gegaran berhenti.'; if(lower.includes('cuaca')) return 'Demo: Saya boleh bantu merumuskan amaran cuaca jika sambungan penyedia AI langsung dikonfigurasi.'; return `Demo: Saya ATAN. Saya menerima arahan anda: “${prompt}”. Mod demo menggunakan jawapan simulasi tanpa kunci API berbayar.`; }
async function timed<T>(fn:()=>Promise<T>):Promise<[T,number]>{const start=performance.now();const value=await fn();return [value,Math.round(performance.now()-start)];}
export const demoAdapter: AiProviderAdapter={id:'demo',label:'Demo ATAN',async test(){return true},async send(request){const [text,responseTimeMs]=await timed(async()=>demoReply(request.prompt));return{text,provider:'demo',simulated:true,responseTimeMs}}};
export const openAiAdapter: AiProviderAdapter={id:'openai',label:'OpenAI',async test(settings){return Boolean(settings.endpoint&&env('VITE_OPENAI_API_KEY'))},async send(request,provider){const [data,responseTimeMs]=await timed(async()=>{const res=await fetch(`${provider.endpoint.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{...jsonHeaders,...authHeaders('openai')},body:JSON.stringify({model:provider.model,messages:[{role:'system',content:'Anda ialah ATAN, pembantu AI bencana untuk Malaysia. Jawab ringkas dalam Bahasa Malaysia.'},...request.messages.map(m=>({role:m.role,content:m.content})),{role:'user',content:request.prompt}]})});if(res.status===401||res.status===403)throw new Error('AUTH_FAILURE');if(!res.ok)throw new Error(`OPENAI_${res.status}`);return res.json()});return{text:data.choices?.[0]?.message?.content??'Tiada respons diterima.',provider:'openai',simulated:false,responseTimeMs}}};
export const geminiAdapter: AiProviderAdapter={id:'gemini',label:'Google Gemini',async test(settings){return Boolean(settings.endpoint&&env('VITE_GEMINI_API_KEY'))},async send(request,provider){const key=env('VITE_GEMINI_API_KEY');const [data,responseTimeMs]=await timed(async()=>{const res=await fetch(`${provider.endpoint.replace(/\/$/,'')}/${provider.model}:generateContent?key=${key}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({contents:[{parts:[{text:`Jawab dalam Bahasa Malaysia sebagai ATAN. ${request.prompt}`}]}]})});if(res.status===401||res.status===403)throw new Error('AUTH_FAILURE');if(!res.ok)throw new Error(`GEMINI_${res.status}`);return res.json()});return{text:data.candidates?.[0]?.content?.parts?.[0]?.text??'Tiada respons diterima.',provider:'gemini',simulated:false,responseTimeMs}}};
export const localAdapter: AiProviderAdapter={id:'local',label:'Local OpenAI-Compatible',async test(settings){return Boolean(settings.endpoint)},async send(request,provider){const [data,responseTimeMs]=await timed(async()=>{const res=await fetch(`${provider.endpoint.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({model:provider.model,messages:[{role:'system',content:'Anda ialah ATAN. Jawab dalam Bahasa Malaysia.'},{role:'user',content:request.prompt}]})});if(!res.ok)throw new Error(`LOCAL_${res.status}`);return res.json()});return{text:data.choices?.[0]?.message?.content??data.message?.content??'Tiada respons diterima.',provider:'local',simulated:false,responseTimeMs}}};
export const adapters={demo:demoAdapter,openai:openAiAdapter,gemini:geminiAdapter,local:localAdapter};
